#!/bin/bash

# Setup Stripe Webhook for Local Development
# This script helps you configure Stripe webhooks for local testing

echo "🚀 Stripe Webhook Setup for Local Development"
echo "============================================="
echo ""

echo "📌 Option 1: Use Stripe CLI (Recommended for development)"
echo "-----------------------------------------------------------"
echo "1. Install Stripe CLI:"
echo "   brew install stripe/stripe-cli/stripe"
echo ""
echo "2. Login to Stripe:"
echo "   stripe login"
echo ""
echo "3. Forward webhooks to local server:"
echo "   stripe listen --forward-to localhost:3000/api/stripe/webhook"
echo ""
echo "4. Copy the webhook signing secret and update .env.local:"
echo "   STRIPE_WEBHOOK_SECRET=whsec_..."
echo ""

echo "📌 Option 2: Configure in Stripe Dashboard (for production)"
echo "-----------------------------------------------------------"
echo "1. Go to: https://dashboard.stripe.com/test/webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Endpoint URL: https://your-domain.com/api/stripe/webhook"
echo "4. Select events:"
echo "   - checkout.session.completed"
echo "   - customer.subscription.created"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "   - invoice.payment_succeeded"
echo "   - invoice.payment_failed"
echo "5. Copy the signing secret to .env.local"
echo ""

echo "📌 Current Configuration:"
echo "-------------------------"
echo "Webhook URL: http://localhost:3000/api/stripe/webhook"
echo ""

echo "📌 Test Cards for Checkout:"
echo "---------------------------"
echo "Success: 4242 4242 4242 4242"
echo "Declined: 4000 0000 0000 0002"
echo "3D Secure: 4000 0027 6000 3184"
echo "SEPA Debit: Use test IBAN from Stripe docs"
echo ""

echo "📌 Testing Flow:"
echo "----------------"
echo "1. Start the development server: npm run dev"
echo "2. Run Stripe CLI listener (see Option 1)"
echo "3. Navigate to: http://localhost:3000/test-stripe"
echo "4. Click 'Go to Pricing Page' and select a plan"
echo "5. Complete checkout with test card"
echo "6. Check webhook events in Stripe CLI output"
echo "7. Verify subscription data on test page"
echo ""

echo "✅ Setup instructions complete!"